name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: myapp
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Test
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
        docker run --rm ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }} npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Kubernetes
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: |
          kubectl set image deployment/myapp-deployment myapp=${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}