name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: myapp

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Test
      run: |
        # Convert repository owner to lowercase
        export REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        export REGISTRY=ghcr.io/$REPO_OWNER
        docker build -t $REGISTRY/${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
        docker run --rm $REGISTRY/${{ env.DOCKER_IMAGE }}:${{ github.sha }} npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        # Convert repository owner to lowercase
        export REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        export REGISTRY=ghcr.io/$REPO_OWNER
        kubectl set image deployment/myapp-deployment myapp=$REGISTRY/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
